apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: gote 
  janus-idp.io/tekton: gote
  backstage.io/kubernetes-id: gote
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gote
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  